version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: caredb
      POSTGRES_USER: careuser
      POSTGRES_PASSWORD: changeme_db_password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - care-net

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/backend.env
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - care-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - '3000:80'
    networks:
      - care-net

volumes:
  db-data:

networks:
  care-net:
    driver: bridge
version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: careride
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@careride.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
volumes:
  db_data:
