version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: caredb
      POSTGRES_USER: careuser
      POSTGRES_PASSWORD: changeme_db_password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - care-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend.env
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - care-net

  # frontend service temporarily removed (frontend sources not present in this repo)
  # To enable later, add frontend/ directory here and restore service definition.

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@careride.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    ports:
      - '5050:80'
    networks:
      - care-net

volumes:
  db-data:

networks:
  care-net:
    driver: bridge
